package com.compass.SPRINGBOOT_AUG_SQUAD_04_Challenge_2.entities;

// Import necessary classes and packages
import com.compass.SPRINGBOOT_AUG_SQUAD_04_Challenge_2.enums.TypeVehicle; // Import the enum
import jakarta.persistence.*;
import lombok.*;

/**
 * The Vacancy class represents a parking vacancy entity in the database.
 * It contains information about the occupancy and capacity of different types of parking.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@Table(name = "vacancy")
@Entity
public class Vacancy {

    /**
     * The unique identifier for the vacancy. It is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The number of occupied spaces for separated parking.
     * This field cannot be null.
     */
    @Column(name = "separated_occupied", nullable = false)
    private Integer separated_ocuppied;

    /**
     * The total capacity for separated parking.
     * This field cannot be null.
     */
    @Column(name = "separated_capacity", nullable = false)
    private Integer separated_capacity;

    /**
     * The number of occupied spaces for monthly parking.
     * This field cannot be null.
     */
    @Column(name = "monthly_occupied", nullable = false)
    private Integer monthly_occupied;

    /**
     * The total capacity for monthly parking.
     * This field cannot be null.
     */
    @Column(name = "monthly_capacity", nullable = false)
    private Integer monthly_capacity;
}
